name: Dummy workflow

on:
  pull_request:
    branches:
      - main

jobs:
  dummy:
    name: Dummy job
    runs-on: ubuntu-latest
    steps:
      - run: echo Haribol

  dummy2:
    name: Dummy job2
    runs-on: ubuntu-latest
    steps:
      - run: echo Haribol2

  build:
    name: Build
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - run: echo Build
