name: Test
on: pull_request

jobs:
  cancel-previous:
    name: Cancel previous workflows
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  detect-changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      functions: ${{ steps.filter.outputs.functions }}
      markdown: ${{ steps.filter.outputs.markdown }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - "frontend/**"
            functions:
              - 'functions/**'

  frontend:
    name: Lint, build and test frontend
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.frontend == 'true' }}
    steps:
      - name: Lint
        run: echo Linted
      - name: Build
        run: echo Built
      - name: Test
        run: echo Tested
      - name: Fail
        run: exit 1

  functions:
    name: Lint, build and test functions
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.functions == 'true' }}
    steps:
      - name: Lint
        run: echo Linted functions
      - name: Build
        run: echo Built functions
      - name: Test
        run: echo Tested functions

  test:
    runs-on: ubuntu-latest
    needs: detect-changes
    strategy:
      matrix:
        project: [frontend, functions]
      fail-fast: false

    name: Test ${{ matrix.project }}

    steps:
      - run: echo ${{ needs.detect-changes.outputs[matrix.project] }}
      - uses: actions/checkout@master
        if: needs.detect-changes.outputs[matrix.project] == 'true'

      - uses: actions/setup-node@v1
        with:
          node-version: 10
        if: needs.detect-changes.outputs[matrix.project] == 'true'

      - name: Cache NPM modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: node-${{ runner.os }}-${{ matrix.project }}-${{ hashFiles(format('{0}/package-lock.json', matrix.project)) }}
          restore-keys: |
            node-${{ runner.os }}-
        if: needs.detect-changes.outputs[matrix.project] == 'true'

      - name: Lint
        run: echo Linted
        if: needs.detect-changes.outputs[matrix.project] == 'true'
      - name: Build
        run: echo Built
        if: needs.detect-changes.outputs[matrix.project] == 'true'
      - name: Test
        run: echo Tested
        if: needs.detect-changes.outputs[matrix.project] == 'true'
