name: Test
on: pull_request

jobs:
  cancel-previous:
    name: Cancel previous workflows
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      functions: ${{ steps.filter.outputs.functions }}
      markdown: ${{ steps.filter.outputs.markdown }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - "frontend/**"
            functions:
              - 'functions/**'
            markdown:
              - '**/**.md'

  frontend:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    steps:
      - name: Lint
        run: echo Linted
      - name: Build
        run: echo Built
      - name: Test
        run: echo Tested

  functions:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.functions == 'true' }}
    steps:
      - name: Lint
        run: echo Linted functions
      - name: Build
        run: echo Built functions
      - name: Test
        run: echo Tested functions

  test:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix:
        project: [frontend, functions]
      fail-fast: false

    name: Test ${{ matrix.project }}
    steps:
      - run: echo "${{ needs.changes.outputs[matrix.project] }}"
      - uses: Thog/action-equals@master
        id: hasChanged
        with:
          a: ${{ needs.changes.outputs[matrix.project] }}
          b: "true"

      - uses: actions/checkout@master
        if: steps.hasChanged.outputs.result

      - uses: actions/setup-node@v1
        with:
          node-version: 10
        if: steps.hasChanged.outputs.result

      - name: Cache NPM modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: node-${{ runner.os }}-${{ matrix.project }}-${{ hashFiles(format('{0}/package-lock.json', matrix.project)) }}
          restore-keys: |
            node-${{ runner.os }}-
        if: steps.hasChanged.outputs.result

      # - run: npm ci
      #   working-directory: ${{ matrix.project }}
      # - run: npm run lint --if-present
      #   working-directory: ${{ matrix.project }}
      # - run: npm run build --if-present
      #   working-directory: ${{ matrix.project }}
      # - run: npm run test --if-present -- --ci
      #   working-directory: ${{ matrix.project }}
      - name: Lint
        run: echo Linted
        if: steps.hasChanged.outputs.result
      - name: Build
        run: echo Built
        if: steps.hasChanged.outputs.result
      - name: Test
        run: echo Tested
        if: steps.hasChanged.outputs.result
