name: Test
on: pull_request

jobs:
  cancel-previous:
    name: Cancel previous workflows
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      functions: ${{ steps.filter.outputs.functions }}
      markdown: ${{ steps.filter.outputs.markdown }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - "frontend/**"
            functions:
              - 'functions/**'
            markdown:
              - '**/**.md'

  frontend:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    steps:
      - name: Lint
        run: echo Linted
      - name: Build
        run: echo Built
      - name: Test
        run: echo Tested

  functions:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    steps:
      - name: Lint
        run: echo Linted functions
      - name: Build
        run: echo Built functions
      - name: Test
        run: echo Tested functions
